R_SCMD = ${R_HOME}/bin${R_ARCH_BIN}/Rscript -e

RINSIDE = $(shell ${R_SCMD} "RInside:::LdFlags()")

CPPFLAGS = $(ALL_CPPFLAGS) -I../xeus/include -I../../inst/include/
CXXFLAGS = $(ALL_CPPFLAGS) -I../xeus/include -I../../inst/include/

LDLIBS = $(ALL_LIBS) $(RINSIDE) -L.. -lxeus
SRC = run.cpp
PRG = $(SRC:.cpp=)

all: $(PRG)

clean:
	rm -vf $(PRG)
	rm -vrf *.dSYM
