language: r
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - CC=gcc-6
    - CXX=g++-6
    - CXX1X=g++-6
    - CXX11=g++-6
    

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
script:
  - g++ --version
  - R CMD INSTALL --build .

after_success:
  - make check
