# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

environment:
  global:
    CRAN: http://cloud.r-project.org/
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    GCC_PATH: mingw_64
    R_CHECK_ARGS: --no-manual

  matrix:
  - R_VERSION: release
    R_ARCH: x64

build_script:
  - set _R_CHECK_FORCE_SUGGESTS_=false
  - travis-tool.sh install_deps
  - cmd.exe /c mk.bat

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits